# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-i386-vagrant-disk1.box'
  config.vm.box = 'ubuntu12.04'

  config.vm.synced_folder "../packages", "/tmp/packages"
  config.vm.provision :shell, :inline => 'yum install -y python-simplejson'
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = '../provisioning/playbook.yml'
    ansible.verbose = 'v'
  end
end
