# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hfm4/centos5"

  config.vm.synced_folder "../packages", "/tmp/packages"
  config.vm.provision :shell, :inline => 'yum install -y python-simplejson'
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = '../provisioning/playbook_rpm.yml'
    ansible.verbose = 'v'
  end
end
