# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-7.0"

  config.vm.synced_folder "../packages", "/tmp/packages"
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = '../provisioning/playbook_rpm.yml'
    ansible.verbose = 'v'

    ENV['STEP'].split(',').each { |s| options[s.to_sym] = true } unless ENV['STEP'].nil?
    ansible.extra_vars = options
  end
end
